spring:
  cloud:
    nacos:
      # Nacos 服务器地址（Config 和 Discovery 共用）
      server-addr: localhost:8848
      # Nacos 认证信息（如果开启了认证）
      username: nacos
      password: nacos
      discovery:
        namespace: c5d6c163-3e4c-42fe-8f97-6c0a032af9d7